// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadListFile() {
  return window['go']['list']['ListParser']['LoadListFile']();
}

export function Parse() {
  return window['go']['list']['ListParser']['Parse']();
}

export function SetContext(arg1) {
  return window['go']['list']['ListParser']['SetContext'](arg1);
}
