// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {list} from '../models';
import {context} from '../models';

export function DeleteListItem(arg1:string):Promise<boolean>;

export function GetBaseItemIDs():Promise<Array<string>>;

export function GetListItemsByIDs(arg1:Array<string>):Promise<Array<list.ListItem>>;

export function GetMainList():Promise<Array<list.ListItem>>;

export function GetSites():Promise<list.Sites>;

export function ListChannels():Promise<void>;

export function NewDbID():Promise<string>;

export function SaveListItem(arg1:list.ListItem):Promise<boolean>;

export function SaveSite(arg1:list.Site):Promise<void>;

export function Search(arg1:string,arg2:list.ListSearchOptions):Promise<Array<list.ListItem>>;

export function SetContext(arg1:context.Context):Promise<void>;
