// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {list} from '../models';
import {context} from '../models';

export function LoadListFile():Promise<Array<list.ListItem>>;

export function Parse():Promise<Array<list.ListItem>>;

export function SetContext(arg1:context.Context):Promise<void>;
