// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBaseItemIDs() {
  return window['go']['list']['List']['GetBaseItemIDs']();
}

export function GetListItemsByIDs(arg1) {
  return window['go']['list']['List']['GetListItemsByIDs'](arg1);
}

export function GetMainList() {
  return window['go']['list']['List']['GetMainList']();
}

export function GetSites() {
  return window['go']['list']['List']['GetSites']();
}

export function ListChannels() {
  return window['go']['list']['List']['ListChannels']();
}

export function NewDbID() {
  return window['go']['list']['List']['NewDbID']();
}

export function SaveListItem(arg1) {
  return window['go']['list']['List']['SaveListItem'](arg1);
}

export function SaveSite(arg1) {
  return window['go']['list']['List']['SaveSite'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['list']['List']['Search'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['list']['List']['SetContext'](arg1);
}
