// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContext() {
  return window['go']['main']['Settings']['GetContext']();
}

export function GetDbAbsolutePath() {
  return window['go']['main']['Settings']['GetDbAbsolutePath']();
}

export function GetSelf() {
  return window['go']['main']['Settings']['GetSelf']();
}

export function OnSync() {
  return window['go']['main']['Settings']['OnSync']();
}

export function Save() {
  return window['go']['main']['Settings']['Save']();
}

export function SetContext(arg1) {
  return window['go']['main']['Settings']['SetContext'](arg1);
}

export function Sync(arg1) {
  return window['go']['main']['Settings']['Sync'](arg1);
}
